
org: amarn19
app: etoken
service: etoken

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha
  - serverless-offline

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name
  serverless-mocha-plugin:
    testTemplate: template/test-template.ejs
    functionTemplate: template/function-template.ejs

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  stage: development
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    ETOKEN_TABLE: ${self:service}-${opt:stage,self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.ETOKEN_TABLE}
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.ETOKEN_TABLE}/index/pk

functions:
  createUser:
    handler: src/functions/createUser.createUser
    description: POST /user/register
    events:
      - http:
          method: post
          path: /user/register
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/createUser_request.json)}
            
  createStore:
    handler: src/functions/createStore.createStore
    description: POST /user/register
    events:
      - http:
          method: post
          path: /user/registerStore
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/createStore_request.json)}
          

  updateRecord:
    handler: src/functions/updateRecord.updateRecord
    description: PATCH /user/updateRecord
    events:
      - http:
          method: patch
          path: /user/updateRecord
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/updateRecord_request.json)}

  bookSlot:
    handler: src/functions/bookSlot.bookSlot
    description: PATCH /user/bookSlot
    events:
      - http:
          method: patch
          path: /user/bookSlot
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
            
  createSlot:
      handler: src/functions/createSlots.createSlots
      description: PATCH /user/createSlot
      events:
        - http:
            method: patch
            path: /user/createSlot
            cors:
              origin: "*"
              headers: ${self:custom.allowedHeaders}

  deleteUser:
    handler: src/functions/deleteUser.deleteUser
    description: DELETE /user/delete
    events:
      - http:
          method: delete
          path: /user/delete
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/deleteUser_request.json)}
  
  getUser:
    handler: src/functions/getUser.getUser
    description: POST /user/fetch
    events:
      - http:
          method: POST
          path: /user/fetch
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/getUser_request.json)}
  
  getUsers:
    handler: src/functions/getUsers.getUsers
    description: GET /user/fetchAll
    events:
      - http:
          method: GET
          path: /user/fetchAll
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
  
  updateUser:
    handler: src/functions/updateUser.updateUser
    description: POST /user/update
    events:
      - http:
          method: POST
          path: /user/update
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
  getStores:
    handler: src/functions/getStores.getStores
    description: POST /user/getStores
    events:
      - http:
          method: POST
          path: /user/getStores
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
          request:
            schema:
              application/json: ${file(src/schema/getStores_request.json)}
resources:
  Resources:
    ETOKENTABLE:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.ETOKEN_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: location
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: etoken-index
            KeySchema:
              - AttributeName: pk
                KeyType: HASH
              - AttributeName: location
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
